spring.data.mongodb.uri=mongodb+srv://Jishankhan:Jishan6263@jishankhan.fcr41.mongodb.net/Easycheckout?retryWrites=true&w=majority
spring.main.banner-mode=off
logging.level.root=INFO
logging.level.org.mongodb.driver=DEBUG
debug=true

razorpay.key_id=rzp_test_SdgsY4Ur72W9Sl
razorpay.key_secret=Di7NkX653JBfaJpQ004kE7J3