spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
server.port=${PORT:8080}

spring.main.banner-mode=off
logging.level.root=INFO
logging.level.org.mongodb.driver=DEBUG
debug=true

razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}